---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-monitoring
resources:
  - kfdef.yaml
  - prometheus/prometheus.yaml
  - prometheus/prometheus-route.yaml
  - grafana/grafana.yaml
  - grafana/grafana-route.yaml
  - dex