apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
    name: grafana
spec:
    baseImage: quay.io/app-sre/grafana:7.1.1
    config:
        server:
            root_url: https://grafana-opf-monitoring.apps.hukhan.dev.datahub.redhat.com
        security:
            admin_user: "root"
            admin_password: "secret"
        auth.anonymous:
            enabled: true
        log:
            level: debug
            mode: console
        auth.generic_oauth:
            name: Dex
            enabled: true
            scopes: openid email groups profile
            email_attribute_name: name
            email_attribute_path: name
            client_id: grafana
            client_secret: secret
            api_url: http://dex-opf-monitoring.apps.hukhan.dev.datahub.redhat.com/userinfo
            auth_url: http://dex-opf-monitoring.apps.hukhan.dev.datahub.redhat.com/auth
            token_url: http://dex-opf-monitoring.apps.hukhan.dev.datahub.redhat.com/token
            role_attribute_path: contains(groups[*], 'operate-first') && 'Admin' || 'Editor'
    dashboardLabelSelector:
    -   matchExpressions:
        -   key: app
            operator: In
            values:
            - grafana
    ingress:
        enabled: false # use our own route to enable insecureEdgeTerminationPolicy