apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/components/jupyterhub
patchesJson6902:
  - target:
      kind: KfDef
      name: opendatahub
      version: v1
      group: kfdef.apps.kubeflow.org
    patch: |
      - op: add
        path: /spec/applications/-
        value:
          kustomizeConfig:
            overlays:
              - storage-class
            parameters:
              - name: s3_endpoint_url
                value: s3.odh.com
              - name: storage_class
                value: ocs-storagecluster-cephfs
            repoRef:
              name: manifests
              path: jupyterhub/jupyterhub
          name: jupyterhub
