---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dex
  annotations:
    serviceaccounts.openshift.io/oauth-redirecturi.grafana:  http://dex-opf-monitoring.apps.hukhan.dev.datahub.redhat.com/callback
